### ISSUE TITLE
Requesting a footer for the webiste

### ISSUE THREAD

**Issue by Akshatchaube01** [Akshatchaube01/Iron-Grit#5]
Create a footer for the website, with some blank space before.
Give contact links as follows :
github: https://github.com/Akshatchaube01
linkedin: https://www.linkedin.com/in/akshat-chaube-b2b042226/
youtube: https://www.youtube.com/
discord: https://discord.gg/pGwV89dfMa
And a message in the end:
Made by Akshat Chaube and Open Source Community

**Comment by Akshatchaube01** [comment]
If you wish to work on this, comment below

**Comment by Akshatchaube01** [comment]
Sure

**Comment by deedee1122** [comment]
Hello, I would like to work on it, you can assign it to me. Thank you

**Comment by Akshatchaube01** [comment]
Hey @deedee1122 , This one has already been assigned, you can check the README for other issues that you can work on : )
